CREATE TABLE institution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE campus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id BIGINT NOT NULL REFERENCES institution(id),
    name VARCHAR(255) NOT NULL
);

CREATE TABLE library (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL REFERENCES campus(id),
    name VARCHAR(255) NOT NULL,
    address TEXT
);

CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_id BIGINT NOT NULL REFERENCES library(id),
    name VARCHAR(255) NOT NULL
);

ALTER TABLE app_user ADD COLUMN department_id BIGINT REFERENCES department(id);

CREATE INDEX idx_campus_institution ON campus(institution_id);
CREATE INDEX idx_library_campus ON library(campus_id);
CREATE INDEX idx_department_library ON department(library_id);
CREATE INDEX idx_user_department ON app_user(department_id);
