CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES category(id),
    name VARCHAR(255) NOT NULL,
    UNIQUE NULLS NOT DISTINCT (parent_id, name),
    CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE TABLE book_title (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author VARCHAR(255),
    publisher VARCHAR(255),
    isbn VARCHAR(20),
    publication_year SMALLINT,
    category_id BIGINT REFERENCES category(id),
    search_vector tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(author, '') || ' ' || coalesce(publisher, ''))
    ) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_book_title_search ON book_title USING GIN(search_vector);
CREATE INDEX idx_book_title_category ON book_title(category_id);

CREATE SEQUENCE book_barcode_sequence START WITH 100001 INCREMENT BY 1;

CREATE TABLE book_copy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_title_id BIGINT NOT NULL REFERENCES book_title(id),
    library_id BIGINT NOT NULL REFERENCES library(id),
    barcode VARCHAR(100) NOT NULL UNIQUE,
    location VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE','BORROWED','LOST','DAMAGED','MAINTENANCE')),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_category_parent ON category(parent_id);
CREATE INDEX idx_copy_title ON book_copy(book_title_id);
CREATE INDEX idx_copy_library_status ON book_copy(library_id, status);
