CREATE TABLE borrowing_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_id BIGINT NOT NULL REFERENCES library(id),
    loan_days INTEGER NOT NULL CHECK (loan_days > 0),
    daily_fine NUMERIC(12,2) NOT NULL CHECK (daily_fine >= 0),
    max_active_loans INTEGER CHECK (max_active_loans > 0),
    effective_from TIMESTAMPTZ NOT NULL,
    UNIQUE (library_id, effective_from)
);

CREATE TABLE borrow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    book_copy_id BIGINT NOT NULL REFERENCES book_copy(id),
    policy_id BIGINT NOT NULL REFERENCES borrowing_policy(id),
    borrowed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    due_at TIMESTAMPTZ NOT NULL,
    returned_at TIMESTAMPTZ,
    daily_fine NUMERIC(12,2) NOT NULL CHECK (daily_fine >= 0),
    fine_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (fine_amount >= 0),
    fine_paid_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'BORROWED' CHECK (status IN ('BORROWED', 'RETURNED')),
    CHECK (due_at > borrowed_at),
    CHECK (returned_at IS NULL OR returned_at >= borrowed_at),
    CHECK ((returned_at IS NULL AND status = 'BORROWED') OR
           (returned_at IS NOT NULL AND status = 'RETURNED'))
);

CREATE UNIQUE INDEX uq_active_borrow_copy ON borrow(book_copy_id) WHERE returned_at IS NULL;
CREATE INDEX idx_borrow_user ON borrow(user_id);
CREATE INDEX idx_borrow_due ON borrow(due_at) WHERE returned_at IS NULL;
CREATE INDEX idx_borrow_policy ON borrow(policy_id);
CREATE INDEX idx_borrow_status ON borrow(status);
