CREATE TABLE digital_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_id BIGINT NOT NULL REFERENCES library(id),
    title TEXT NOT NULL,
    description TEXT,
    publisher VARCHAR(255),
    category_id BIGINT REFERENCES category(id),
    storage_key VARCHAR(512) NOT NULL UNIQUE,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','PENDING','APPROVED','PUBLISHED')),
    permission VARCHAR(20) NOT NULL DEFAULT 'RESTRICTED' CHECK (permission IN ('AUTHENTICATED','RESTRICTED')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE document_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES digital_document(id) ON DELETE CASCADE,
    institution_id BIGINT REFERENCES institution(id),
    campus_id BIGINT REFERENCES campus(id),
    department_id BIGINT REFERENCES department(id),
    user_id BIGINT REFERENCES app_user(id),
    CHECK (num_nonnulls(institution_id, campus_id, department_id, user_id) = 1),
    UNIQUE NULLS NOT DISTINCT (document_id, institution_id, campus_id, department_id, user_id)
);

CREATE INDEX idx_document_library ON digital_document(library_id);
CREATE INDEX idx_document_category ON digital_document(category_id);
CREATE INDEX idx_document_status ON digital_document(status);
CREATE INDEX idx_document_permission ON digital_document(permission);
CREATE INDEX idx_document_is_active ON digital_document(is_active);
CREATE INDEX idx_grant_document ON document_grant(document_id);
CREATE INDEX idx_grant_institution ON document_grant(institution_id);
CREATE INDEX idx_grant_campus ON document_grant(campus_id);
CREATE INDEX idx_grant_department ON document_grant(department_id);
CREATE INDEX idx_grant_user ON document_grant(user_id);
