CREATE TABLE physical_reading_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    book_copy_id BIGINT NOT NULL REFERENCES book_copy(id),
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    CHECK (ended_at IS NULL OR ended_at >= started_at)
);

CREATE TABLE digital_reading_session (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    document_id BIGINT NOT NULL REFERENCES digital_document(id),
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at TIMESTAMPTZ,
    active_seconds BIGINT NOT NULL DEFAULT 0 CHECK (active_seconds >= 0),
    CHECK (last_seen_at >= started_at),
    CHECK (ended_at IS NULL OR ended_at >= started_at)
);

CREATE TABLE reading_heartbeat (
    session_id UUID NOT NULL REFERENCES digital_reading_session(id) ON DELETE CASCADE,
    sequence_number BIGINT NOT NULL CHECK (sequence_number >= 0),
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    active BOOLEAN NOT NULL,
    visible BOOLEAN NOT NULL,
    PRIMARY KEY (session_id, sequence_number)
);

CREATE TABLE digital_reading_summary (
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    document_id BIGINT NOT NULL REFERENCES digital_document(id),
    active_seconds BIGINT NOT NULL DEFAULT 0 CHECK (active_seconds >= 0),
    session_count BIGINT NOT NULL DEFAULT 0 CHECK (session_count >= 0),
    last_active_at TIMESTAMPTZ,
    PRIMARY KEY (user_id, document_id)
);

CREATE INDEX idx_reading_user ON digital_reading_session(user_id, started_at);
CREATE INDEX idx_reading_doc ON digital_reading_session(document_id);
CREATE INDEX idx_heartbeat_time ON reading_heartbeat(session_id, received_at);
CREATE INDEX idx_summary_user ON digital_reading_summary(user_id);
CREATE INDEX idx_physical_reading_user ON physical_reading_session(user_id, started_at);
CREATE INDEX idx_physical_reading_copy ON physical_reading_session(book_copy_id);
