CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    borrow_id BIGINT REFERENCES borrow(id),
    notification_type VARCHAR(50) NOT NULL CHECK (notification_type IN ('DUE_REMINDER','OVERDUE','SYSTEM')),
    channel VARCHAR(20) NOT NULL DEFAULT 'EMAIL' CHECK (channel IN ('EMAIL','IN_APP')),
    title VARCHAR(255) NOT NULL DEFAULT 'Thông báo Thư viện',
    message TEXT NOT NULL,
    deduplication_key VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','SENT','FAILED')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_notification_retry ON notification(next_attempt_at) WHERE status <> 'SENT';
CREATE INDEX idx_notification_user ON notification(user_id, created_at DESC);
CREATE INDEX idx_notification_dedup ON notification(deduplication_key);
