CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_user(id),
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(100),
    resource_id VARCHAR(100),
    request_id VARCHAR(100),
    details TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_log_user ON audit_log(user_id);
CREATE INDEX idx_audit_log_created_at ON audit_log(created_at DESC);
CREATE INDEX idx_audit_log_action ON audit_log(action);

CREATE TABLE system_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(100) NOT NULL UNIQUE,
    value TEXT NOT NULL,
    description VARCHAR(255),
    is_secret BOOLEAN NOT NULL DEFAULT false,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by BIGINT REFERENCES app_user(id)
);

CREATE INDEX idx_system_setting_key ON system_setting(key);

-- Seed default settings
INSERT INTO system_setting (key, value, description, is_secret) VALUES
('library.name', 'Thư viện Đại học Phú Xuân', 'Tên chính thức của thư viện hiển thị trên hệ thống', false),
('library.max_loan_days', '14', 'Số ngày mượn sách vật lý tiêu chuẩn', false),
('library.max_books_per_user', '5', 'Số lượng sách mượn tối đa cùng lúc cho mỗi độc giả', false),
('library.daily_fine_amount', '5000', 'Tiền phạt quá hạn mỗi ngày cho một cuốn sách (VNĐ)', false),
('library.email_notification_enabled', 'true', 'Bật / tắt dịch vụ gửi email thông báo tự động', false),
('library.smtp_password', 'secret_token_placeholder', 'Mật khẩu ứng dụng SMTP dùng cho gửi thư viện', true);
