-- PHASE 0 DESIGN, NOT a phase 1 migration. PostgreSQL 17.
-- Tests execute this file in an isolated schema. Introduce domain migrations per phase.
CREATE TABLE institution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE campus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institution_id BIGINT NOT NULL REFERENCES institution(id),
    name VARCHAR(255) NOT NULL
);
CREATE TABLE library (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campus_id BIGINT NOT NULL REFERENCES campus(id),
    name VARCHAR(255) NOT NULL,
    address TEXT
);
CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_id BIGINT NOT NULL REFERENCES library(id),
    name VARCHAR(255) NOT NULL
);
CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_subject VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    student_code VARCHAR(50) UNIQUE,
    department_id BIGINT REFERENCES department(id),
    role VARCHAR(20) NOT NULL CHECK (role IN ('STUDENT','LECTURER','LIBRARIAN','ADMIN')),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_user_email ON app_user(lower(email));
-- Campus/institution are derived through department; never accept conflicting client IDs.
-- OIDC sessions are stored in Redis in phase 2, not plaintext token tables.
CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT REFERENCES category(id),
    name VARCHAR(255) NOT NULL,
    UNIQUE NULLS NOT DISTINCT (parent_id, name),
    CHECK (parent_id IS NULL OR parent_id <> id)
);
-- Version policy rows instead of changing historical loan terms.
-- No invented default loan duration, daily fine or borrowing limit.
CREATE TABLE borrowing_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_id BIGINT NOT NULL REFERENCES library(id),
    loan_days INTEGER NOT NULL CHECK (loan_days > 0),
    daily_fine NUMERIC(12,2) NOT NULL CHECK (daily_fine >= 0),
    max_active_loans INTEGER CHECK (max_active_loans > 0),
    effective_from TIMESTAMPTZ NOT NULL,
    UNIQUE (library_id, effective_from)
);
CREATE TABLE book_title (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author VARCHAR(255),
    publisher VARCHAR(255),
    isbn VARCHAR(20),
    publication_year SMALLINT,
    category_id BIGINT REFERENCES category(id),
    search_vector tsvector GENERATED ALWAYS AS (
        to_tsvector('simple', coalesce(title,'') || ' ' || coalesce(author,'') || ' ' || coalesce(publisher,''))
    ) STORED,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_book_title_search ON book_title USING GIN(search_vector);
CREATE SEQUENCE book_barcode_sequence;
CREATE TABLE book_copy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_title_id BIGINT NOT NULL REFERENCES book_title(id),
    library_id BIGINT NOT NULL REFERENCES library(id),
    barcode VARCHAR(100) NOT NULL UNIQUE,
    location VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE','BORROWED','LOST','DAMAGED','MAINTENANCE')),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE borrow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    book_copy_id BIGINT NOT NULL REFERENCES book_copy(id),
    policy_id BIGINT NOT NULL REFERENCES borrowing_policy(id),
    borrowed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    due_at TIMESTAMPTZ NOT NULL,
    returned_at TIMESTAMPTZ,
    daily_fine NUMERIC(12,2) NOT NULL CHECK (daily_fine >= 0),
    fine_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (fine_amount >= 0),
    fine_paid_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL DEFAULT 'BORROWED',
    CHECK (due_at > borrowed_at),
    CHECK (returned_at IS NULL OR returned_at >= borrowed_at),
    CHECK ((returned_at IS NULL AND status = 'BORROWED') OR
           (returned_at IS NOT NULL AND status = 'RETURNED'))
);
CREATE UNIQUE INDEX uq_active_borrow_copy ON borrow(book_copy_id) WHERE returned_at IS NULL;
CREATE INDEX idx_borrow_user ON borrow(user_id);
CREATE INDEX idx_borrow_due ON borrow(due_at) WHERE returned_at IS NULL;
CREATE INDEX idx_copy_title ON book_copy(book_title_id);
CREATE INDEX idx_copy_library_status ON book_copy(library_id,status);
CREATE TABLE physical_reading_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    book_copy_id BIGINT NOT NULL REFERENCES book_copy(id),
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    CHECK (ended_at IS NULL OR ended_at >= started_at)
);
CREATE TABLE digital_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    library_id BIGINT NOT NULL REFERENCES library(id),
    title TEXT NOT NULL,
    description TEXT,
    publisher VARCHAR(255),
    category_id BIGINT REFERENCES category(id),
    storage_key VARCHAR(512) NOT NULL UNIQUE,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','PENDING','APPROVED','PUBLISHED')),
    permission VARCHAR(20) NOT NULL DEFAULT 'RESTRICTED' CHECK (permission IN ('AUTHENTICATED','RESTRICTED')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE document_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES digital_document(id) ON DELETE CASCADE,
    institution_id BIGINT REFERENCES institution(id),
    campus_id BIGINT REFERENCES campus(id),
    department_id BIGINT REFERENCES department(id),
    user_id BIGINT REFERENCES app_user(id),
    CHECK (num_nonnulls(institution_id,campus_id,department_id,user_id) = 1),
    UNIQUE NULLS NOT DISTINCT (document_id,institution_id,campus_id,department_id,user_id)
);
CREATE TABLE digital_reading_session (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    document_id BIGINT NOT NULL REFERENCES digital_document(id),
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at TIMESTAMPTZ,
    active_seconds BIGINT NOT NULL DEFAULT 0 CHECK (active_seconds >= 0),
    CHECK (last_seen_at >= started_at),
    CHECK (ended_at IS NULL OR ended_at >= started_at)
);
CREATE TABLE reading_heartbeat (
    session_id UUID NOT NULL REFERENCES digital_reading_session(id),
    sequence_number BIGINT NOT NULL CHECK (sequence_number >= 0),
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    active BOOLEAN NOT NULL,
    visible BOOLEAN NOT NULL,
    PRIMARY KEY (session_id, sequence_number)
);
CREATE TABLE digital_reading_summary (
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    document_id BIGINT NOT NULL REFERENCES digital_document(id),
    active_seconds BIGINT NOT NULL DEFAULT 0 CHECK (active_seconds >= 0),
    session_count BIGINT NOT NULL DEFAULT 0 CHECK (session_count >= 0),
    last_active_at TIMESTAMPTZ,
    PRIMARY KEY (user_id, document_id)
);
CREATE INDEX idx_reading_user ON digital_reading_session(user_id,started_at);
CREATE INDEX idx_document_category ON digital_document(category_id);
CREATE TABLE notification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    borrow_id BIGINT REFERENCES borrow(id),
    notification_type VARCHAR(50) NOT NULL CHECK (notification_type IN ('DUE_REMINDER','OVERDUE','SYSTEM')),
    channel VARCHAR(20) NOT NULL DEFAULT 'EMAIL' CHECK (channel IN ('EMAIL','IN_APP')),
    message TEXT NOT NULL,
    deduplication_key VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','SENT','FAILED')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notification_retry ON notification(next_attempt_at) WHERE status <> 'SENT';
CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES app_user(id),
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(100),
    resource_id VARCHAR(100),
    request_id UUID,
    details JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- Application enforces: organization scope, category cycles, copy/loan state in one
-- transaction, grant checks, session ownership, bounded server-counted reading time,
-- notification retry limits, and redacted append-only audit logs.
